[package]
name = "passgen"
version = "0.6.1"
edition = "2026"

[[bin]]
name = "passgen"
path = "src/main.rs"

[dependencies]
pbkdf2 = { version = "0.12", features = ["simple"] }
argon2 = "0.5"
hmac = "0.12"
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
getrandom = "0.2"
rpassword = "7"
base64 = "0.22"

[target.'cfg(unix)'.dependencies]
termios = "0.3"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
arboard = "3"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }
